/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bf11cae1-187b-4d5d-a997-9bc30769c42a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Zt6xnb3ZN",
    "aws_user_pools_web_client_id": "5ckb5vht67vmgagqr3k00tjbio",
    "oauth": {}
};


export default awsmobile;
